"""empty message

Revision ID: 238edc55c018
Revises: 8554df5682f9
Create Date: 2021-08-23 15:19:27.385933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238edc55c018'
down_revision = '8554df5682f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pickleKey', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'pickleKey')
    # ### end Alembic commands ###
