"""empty message

Revision ID: e76ba9cb0954
Revises: ff393b792b50
Create Date: 2021-07-07 15:13:06.885011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76ba9cb0954'
down_revision = 'ff393b792b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machineId', sa.String(length=200), nullable=True),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('inUse', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['license.getKey'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('key')
    # ### end Alembic commands ###
