"""empty message

Revision ID: fc16b7b7c136
Revises: 238edc55c018
Create Date: 2021-08-23 15:34:00.054707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc16b7b7c136'
down_revision = '238edc55c018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pickleKey', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'pickleKey')
    # ### end Alembic commands ###
