"""empty message

Revision ID: ff393b792b50
Revises: 886836fdf866
Create Date: 2021-07-07 14:50:56.781310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff393b792b50'
down_revision = '886836fdf866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('key', sa.Column('machineId', sa.String(length=200), nullable=True))
    op.drop_constraint('key_owner_id_fkey', 'key', type_='foreignkey')
    op.create_foreign_key(None, 'key', 'license', ['owner_id'], ['getKey'])
    op.drop_column('key', 'keyId')
    op.drop_column('key', 'key')
    op.drop_column('license', 'id')
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.add_column('license', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('license_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('key', sa.Column('key', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('key', sa.Column('keyId', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'key', type_='foreignkey')
    op.create_foreign_key('key_owner_id_fkey', 'key', 'license', ['owner_id'], ['id'])
    op.drop_column('key', 'machineId')
    op.drop_column('key', 'id')
    # ### end Alembic commands ###
