"""empty message

Revision ID: 6d3d9de33c6e
Revises: e76ba9cb0954
Create Date: 2021-07-22 14:48:27.437621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3d9de33c6e'
down_revision = 'e76ba9cb0954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('key_owner_id_fkey', 'key', type_='foreignkey')
    op.create_foreign_key(None, 'key', 'license', ['owner_id'], ['getKey'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'key', type_='foreignkey')
    op.create_foreign_key('key_owner_id_fkey', 'key', 'license', ['owner_id'], ['getKey'])
    # ### end Alembic commands ###
