"""empty message

Revision ID: 8473b5b25a90
Revises: fc16b7b7c136
Create Date: 2021-08-23 15:44:43.692233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8473b5b25a90'
down_revision = 'fc16b7b7c136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pickleKey', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'pickleKey')
    # ### end Alembic commands ###
