"""empty message

Revision ID: 8ca24f55ed1b
Revises: 35f454c70f28
Create Date: 2021-10-29 08:38:46.782326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca24f55ed1b'
down_revision = '35f454c70f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logger',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logger')
    # ### end Alembic commands ###
