"""empty message

Revision ID: 92b009323d0b
Revises: 6d3d9de33c6e
Create Date: 2021-07-22 14:53:09.048612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b009323d0b'
down_revision = '6d3d9de33c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('license_owner_email_fkey', 'license', type_='foreignkey')
    op.create_foreign_key(None, 'license', 'user', ['owner_email'], ['email'], onupdate='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'license', type_='foreignkey')
    op.create_foreign_key('license_owner_email_fkey', 'license', 'user', ['owner_email'], ['email'])
    # ### end Alembic commands ###
