"""empty message

Revision ID: c860c7ca9aa4
Revises: 8473b5b25a90
Create Date: 2021-08-23 16:01:22.076171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c860c7ca9aa4'
down_revision = '8473b5b25a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pickleKey', sa.String(length=80), server_default='21f55e06-e921-4148-ba42-a8a03adc6b0c', nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'pickleKey')
    # ### end Alembic commands ###
