"""empty message

Revision ID: d771666e4b88
Revises: 92b009323d0b
Create Date: 2021-07-25 16:35:06.485300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd771666e4b88'
down_revision = '92b009323d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('lastAccess', sa.DateTime(), nullable=True))
    op.add_column('key', sa.Column('lastIP', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', 'lastIP')
    op.drop_column('key', 'lastAccess')
    # ### end Alembic commands ###
